# Generated by Django 4.2.9 on 2025-10-26 09:34

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("emp", "0018_rename_contact_contacts"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                ("serial_no", models.AutoField(primary_key=True, serialize=False)),
                (
                    "entry_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Entry Date"
                    ),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("Hospital", "Hospital"),
                            ("Institute", "Institute"),
                            ("Event", "Event"),
                            ("Hostel", "Hostel"),
                        ],
                        default="Hospital",
                        max_length=20,
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        max_length=200, verbose_name="Hospital / Customer Name"
                    ),
                ),
                (
                    "total_beds",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Total Beds"
                    ),
                ),
                (
                    "current_occupancy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Current Occupancy (%)",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        max_length=100, verbose_name="Contact Person Name"
                    ),
                ),
                ("designation", models.CharField(max_length=100)),
                ("mobile_no", models.CharField(max_length=15)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "address",
                    models.TextField(verbose_name="Complete Address / Location"),
                ),
                (
                    "existing_vendor",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Existing Vendor / Caterer",
                    ),
                ),
                (
                    "service_requirement",
                    models.CharField(
                        choices=[
                            ("Diet Service", "Diet Service"),
                            ("Cafeteria", "Cafeteria"),
                            ("Event Catering", "Event Catering"),
                            ("Others", "Others"),
                        ],
                        max_length=20,
                        verbose_name="Service Requirement",
                    ),
                ),
                (
                    "lead_status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("In Progress", "In Progress"),
                            ("Quoted", "Quoted"),
                            ("Converted", "Converted"),
                            ("Not Interested", "Not Interested"),
                            ("Closed", "Closed"),
                        ],
                        default="New",
                        max_length=20,
                    ),
                ),
                (
                    "next_follow_up",
                    models.DateField(
                        blank=True, null=True, verbose_name="Next Follow-up Date"
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True, null=True, verbose_name="Remarks / Notes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "converted_site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_source",
                        to="emp.site",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads_created",
                        to="emp.employee",
                        verbose_name="Sales Employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Potential Site Lead",
                "verbose_name_plural": "Potential Site Leads",
                "db_table": "leads",
                "ordering": ["-entry_date"],
            },
        ),
        migrations.CreateModel(
            name="LeadConversionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conversion_date", models.DateTimeField(auto_now_add=True)),
                (
                    "remarks",
                    models.TextField(
                        blank=True, null=True, verbose_name="Conversion Notes"
                    ),
                ),
                (
                    "converted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversions_made",
                        to="emp.employee",
                        verbose_name="Converted By",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversion_logs",
                        to="leads.lead",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_conversions",
                        to="emp.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Conversion Log",
                "verbose_name_plural": "Lead Conversion Logs",
                "db_table": "lead_conversion_logs",
                "ordering": ["-conversion_date"],
            },
        ),
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateField(verbose_name="Last Follow-Up Date"),
                ),
                (
                    "feedback",
                    models.CharField(
                        choices=[
                            ("Positive", "Positive"),
                            ("Negative", "Negative"),
                            ("Neutral", "Neutral"),
                        ],
                        max_length=20,
                        verbose_name="Feedback",
                    ),
                ),
                (
                    "quotation_sent",
                    models.BooleanField(default=False, verbose_name="Quotation Sent"),
                ),
                (
                    "quotation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Quotation Date"
                    ),
                ),
                (
                    "closing_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Closing Date"
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_ups_created",
                        to="emp.employee",
                        verbose_name="Sales Employee",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_ups",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Follow-up",
                "verbose_name_plural": "Lead Follow-ups",
                "db_table": "lead_follow_ups",
                "ordering": ["-follow_up_date"],
            },
        ),
    ]
