# Generated by Django 4.2.9 on 2025-10-26 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lead",
            old_name="serial_no",
            new_name="lead_id",
        ),
    ]
