# Generated by Django 4.2.9 on 2025-12-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_rename_serial_no_lead_lead_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="followup",
            name="next_follow_up_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Next Follow-up Date"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="has_service_requirement",
            field=models.BooleanField(
                default=False, verbose_name="Has Service Requirement?"
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="service_requirement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Diet Service", "Diet Service"),
                    ("Cafeteria", "Cafeteria"),
                    ("Event Catering", "Event Catering"),
                    ("Others", "Others"),
                ],
                max_length=20,
                null=True,
                verbose_name="Service Requirement",
            ),
        ),
    ]
