# Generated by Django 4.2.9 on 2025-12-10 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_followup_next_follow_up_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Contact Name")),
                (
                    "designation",
                    models.CharField(max_length=100, verbose_name="Designation"),
                ),
                ("mobile1", models.CharField(max_length=15, verbose_name="Mobile 1")),
                (
                    "mobile2",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Mobile 2"
                    ),
                ),
                (
                    "landline",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Landline"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Address"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="leads.lead",
                        verbose_name="Lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Contact",
                "verbose_name_plural": "Lead Contacts",
                "db_table": "lead_contacts",
                "ordering": ["-created_at"],
            },
        ),
    ]
