# Generated by Django 4.2.9 on 2025-12-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0004_leadcontact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leadcontact",
            name="address",
        ),
    ]
