# Generated by Django 4.2.9 on 2025-12-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0005_remove_address_from_leadcontact"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadcontact",
            name="remarks",
            field=models.TextField(blank=True, null=True, verbose_name="Remarks"),
        ),
    ]
