# Generated by Django 4.2.9 on 2026-04-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0006_add_remarks_to_leadcontact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followup",
            name="follow_up_date",
            field=models.DateField(verbose_name="Date of Contact"),
        ),
    ]
