# Generated by Django 4.2.9 on 2025-12-10 17:41

import apps.vendors.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                ("vendor_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "vendor_code",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "vendor_name",
                    models.CharField(
                        max_length=200, verbose_name="Vendor/Company Name"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        max_length=100, verbose_name="Contact Person Name"
                    ),
                ),
                (
                    "designation",
                    models.CharField(max_length=100, verbose_name="Designation"),
                ),
                (
                    "mobile_no",
                    models.CharField(max_length=15, verbose_name="Mobile Number"),
                ),
                (
                    "mobile_no_2",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Alternate Mobile",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="Email Address",
                    ),
                ),
                ("address", models.TextField(verbose_name="Complete Address")),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="City"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AN", "Andaman and Nicobar Islands"),
                            ("AP", "Andhra Pradesh"),
                            ("AR", "Arunachal Pradesh"),
                            ("AS", "Assam"),
                            ("BR", "Bihar"),
                            ("CH", "Chandigarh"),
                            ("CT", "Chhattisgarh"),
                            ("DH", "Dadra and Nagar Haveli and Daman and Diu"),
                            ("DL", "Delhi"),
                            ("GA", "Goa"),
                            ("GJ", "Gujarat"),
                            ("HR", "Haryana"),
                            ("HP", "Himachal Pradesh"),
                            ("JK", "Jammu and Kashmir"),
                            ("JH", "Jharkhand"),
                            ("KA", "Karnataka"),
                            ("KL", "Kerala"),
                            ("LA", "Ladakh"),
                            ("LD", "Lakshadweep"),
                            ("MP", "Madhya Pradesh"),
                            ("MH", "Maharashtra"),
                            ("MN", "Manipur"),
                            ("ML", "Meghalaya"),
                            ("MZ", "Mizoram"),
                            ("NL", "Nagaland"),
                            ("OR", "Odisha"),
                            ("PY", "Puducherry"),
                            ("PB", "Punjab"),
                            ("RJ", "Rajasthan"),
                            ("SK", "Sikkim"),
                            ("TN", "Tamil Nadu"),
                            ("TG", "Telangana"),
                            ("TR", "Tripura"),
                            ("UP", "Uttar Pradesh"),
                            ("UT", "Uttarakhand"),
                            ("WB", "West Bengal"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="State",
                    ),
                ),
                (
                    "pincode",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="PIN Code"
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("Supplier", "Supplier"),
                            ("Contractor", "Contractor"),
                            ("Service Provider", "Service Provider"),
                            ("Manufacturer", "Manufacturer"),
                            ("Distributor", "Distributor"),
                            ("Other", "Other"),
                        ],
                        max_length=30,
                        verbose_name="Business Type",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Vendor Category",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("Suspended", "Suspended"),
                            ("Blacklisted", "Blacklisted"),
                        ],
                        default="Active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True, null=True, verbose_name="Remarks/Notes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendors_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor",
                "verbose_name_plural": "Vendors",
                "db_table": "vendors",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VendorPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("Cheque", "Cheque"),
                            ("Net Banking", "Net Banking"),
                            ("Bank Transfer", "Bank Transfer"),
                            ("UPI", "UPI"),
                        ],
                        max_length=20,
                        verbose_name="Payment Mode",
                    ),
                ),
                (
                    "payment_schedule_value",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Payment Schedule (Number)",
                    ),
                ),
                (
                    "payment_schedule_unit",
                    models.CharField(
                        choices=[
                            ("Days", "Days"),
                            ("Weeks", "Weeks"),
                            ("Months", "Months"),
                        ],
                        max_length=10,
                        verbose_name="Payment Schedule Unit",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Bank Name"
                    ),
                ),
                (
                    "account_holder_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Account Holder Name",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Account Number",
                    ),
                ),
                (
                    "ifsc_code",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid IFSC code",
                                regex="^[A-Z]{4}0[A-Z0-9]{6}$",
                            )
                        ],
                        verbose_name="IFSC Code",
                    ),
                ),
                (
                    "branch_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Branch Name",
                    ),
                ),
                (
                    "upi_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="UPI ID"
                    ),
                ),
                (
                    "cancelled_cheque",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.vendors.models.get_cancelled_cheque_upload_path,
                        verbose_name="Cancelled Cheque",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_info",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor Payment Information",
                "verbose_name_plural": "Vendor Payment Information",
                "db_table": "vendor_payment_info",
            },
        ),
        migrations.CreateModel(
            name="VendorDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("Quotation", "Quotation"),
                            ("Contract", "Contract"),
                            ("Agreement", "Agreement"),
                            ("Cancelled Cheque", "Cancelled Cheque"),
                            ("Registration Certificate", "Registration Certificate"),
                            ("Other", "Other"),
                        ],
                        max_length=30,
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "document_file",
                    models.FileField(
                        upload_to=apps.vendors.models.get_vendor_document_upload_path,
                        verbose_name="Document File",
                    ),
                ),
                (
                    "document_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Document Name/Description",
                    ),
                ),
                (
                    "upload_date",
                    models.DateField(auto_now_add=True, verbose_name="Upload Date"),
                ),
                (
                    "valid_until",
                    models.DateField(blank=True, null=True, verbose_name="Valid Until"),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, null=True, verbose_name="Remarks"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_documents_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor Document",
                "verbose_name_plural": "Vendor Documents",
                "db_table": "vendor_documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VendorRegistrationID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("PAN Card", "PAN Card"),
                            ("Aadhaar", "Aadhaar"),
                            ("GST", "GST"),
                            ("Udyam", "Udyam"),
                        ],
                        max_length=20,
                        verbose_name="ID Type",
                    ),
                ),
                (
                    "id_number",
                    models.CharField(max_length=50, verbose_name="ID Number"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Primary ID"),
                ),
                (
                    "document_upload",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.vendors.models.get_vendor_id_upload_path,
                        verbose_name="ID Document",
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(default=False, verbose_name="Verified"),
                ),
                (
                    "verification_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Verification Date"
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, null=True, verbose_name="Remarks"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_ids",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor Registration ID",
                "verbose_name_plural": "Vendor Registration IDs",
                "db_table": "vendor_registration_ids",
                "ordering": ["-is_primary", "-created_at"],
                "unique_together": {("vendor", "id_type")},
            },
        ),
    ]
