# Generated by Django 4.2.9 on 2025-08-06 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("emp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="designation",
            name="department",
        ),
        migrations.AddField(
            model_name="contact",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Active",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Active",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="designation",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Active",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="emp.department",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="photo",
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="status",
            field=models.CharField(
                choices=[
                    ("InActive", "InActive"),
                    ("Active", "Active"),
                    ("Terminated", "Terminated"),
                    ("Suspended", "Suspended"),
                    ("On Leave", "On Leave"),
                    ("Leave of Absence", "Leave of Absence"),
                    ("Maternity/Paternity Leave", "Maternity/Paternity Leave"),
                    ("Medical Leave", "Medical Leave"),
                    ("Sabbatical", "Sabbatical"),
                    ("Pre-Hire", "Pre-Hire"),
                    ("Onboarding", "Onboarding"),
                    ("Probation", "Probation"),
                    ("Retired", "Retired"),
                    ("Archived", "Archived"),
                ],
                default="InActive",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="employeeupload",
            name="status",
            field=models.CharField(
                choices=[
                    ("Verified", "Verified"),
                    ("UnVerified", "UnVerified"),
                    ("Rejected", "Rejected"),
                    ("Deleted", "Deleted"),
                    ("Pending", "Pending"),
                ],
                default="Pending",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="status",
            field=models.CharField(
                choices=[
                    ("Approved", "Approved"),
                    ("Pending", "Pending"),
                    ("Rejected", "Rejected"),
                ],
                default="Approved",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="department",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="designation",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
