# Generated by Django 4.2.9 on 2025-08-06 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("emp", "0002_remove_designation_department_contact_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="emp.department",
            ),
        ),
    ]
