# Generated by Django 4.2.9 on 2025-08-06 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("emp", "0004_alter_employee_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="emp.site",
            ),
        ),
    ]
