# Generated by Django 4.2.9 on 2025-08-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp", "0005_alter_employee_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="site",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="site",
            name="pincode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="site",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
