# Generated by Django 4.2.9 on 2025-08-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp", "0006_alter_site_address_alter_site_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="pincode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
