# Generated by Django 4.2.9 on 2025-08-12 19:17

import apps.emp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("emp", "0008_contact_address_contact_city_contact_pincode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.emp.models.get_photo_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="employeeupload",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employeeupload",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("Aadhaar", "Aadhaar"),
                    ("PAN", "PAN"),
                    ("Passport", "Passport"),
                    ("Driving License", "Driving License"),
                    ("Voter ID", "Voter ID"),
                    ("Report", "Report"),
                    ("Bill", "Bill"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="employeeupload",
            name="file_path",
            field=models.FileField(upload_to=apps.emp.models.get_file_upload_path),
        ),
        migrations.AlterField(
            model_name="employeeupload",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="employeeupload",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
