# Generated by Django 4.2.9 on 2025-08-12 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emp", "0009_alter_employee_photo_and_more"),
    ]

    operations = []
