# Generated by Django 4.2.9 on 2025-08-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp", "0010_auto_20250813_0056"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="address",
            new_name="cor_address",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="city",
            new_name="cor_city",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="pincode",
            new_name="cor_pincode",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="state",
            new_name="cor_state",
        ),
        migrations.AddField(
            model_name="employee",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                ],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_alternative_no",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_person_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_relation",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="father_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Single", "Single"),
                    ("Married", "Married"),
                    ("Divorced", "Divorced"),
                    ("Widowed", "Widowed"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="mother_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="nationality",
            field=models.CharField(
                choices=[
                    ("Indian", "Indian"),
                    ("Nepali", "Nepali"),
                    ("Other", "Other"),
                ],
                default="Indian",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="passport_no",
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="per_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="per_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="per_pincode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="per_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AN", "Andaman and Nicobar Islands"),
                    ("AP", "Andhra Pradesh"),
                    ("AR", "Arunachal Pradesh"),
                    ("AS", "Assam"),
                    ("BR", "Bihar"),
                    ("CH", "Chandigarh"),
                    ("CT", "Chhattisgarh"),
                    ("DH", "Dadra and Nagar Haveli and Daman and Diu"),
                    ("DL", "Delhi"),
                    ("GA", "Goa"),
                    ("GJ", "Gujarat"),
                    ("HR", "Haryana"),
                    ("HP", "Himachal Pradesh"),
                    ("JK", "Jammu and Kashmir"),
                    ("JH", "Jharkhand"),
                    ("KA", "Karnataka"),
                    ("KL", "Kerala"),
                    ("LA", "Ladakh"),
                    ("LD", "Lakshadweep"),
                    ("MP", "Madhya Pradesh"),
                    ("MH", "Maharashtra"),
                    ("MN", "Manipur"),
                    ("ML", "Meghalaya"),
                    ("MZ", "Mizoram"),
                    ("NL", "Nagaland"),
                    ("OR", "Odisha"),
                    ("PY", "Puducherry"),
                    ("PB", "Punjab"),
                    ("RJ", "Rajasthan"),
                    ("SK", "Sikkim"),
                    ("TN", "Tamil Nadu"),
                    ("TG", "Telangana"),
                    ("TR", "Tripura"),
                    ("UP", "Uttar Pradesh"),
                    ("UT", "Uttarakhand"),
                    ("WB", "West Bengal"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="pf_esic_no",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="uan_no",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="other_id_proof_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Voter ID", "Voter ID"),
                    ("Driving Licence No.", "Driving Licence No."),
                    ("International ID", "International ID"),
                    ("Other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("aadhaar_no__isnull", False),
                    models.Q(("aadhaar_no", ""), _negated=True),
                ),
                fields=("aadhaar_no",),
                name="unique_non_empty_aadhaar_no",
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("pan_card__isnull", False),
                    models.Q(("pan_card", ""), _negated=True),
                ),
                fields=("pan_card",),
                name="unique_non_empty_pan_card",
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("passport_no__isnull", False),
                    models.Q(("passport_no", ""), _negated=True),
                ),
                fields=("passport_no",),
                name="unique_non_empty_passport_no",
            ),
        ),
    ]



