# Generated by Django 4.2.9 on 2025-08-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp", "0011_rename_address_employee_cor_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="middle_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]



