# Generated by Django 4.2.9 on 2025-08-22 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("emp", "0012_employee_middle_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeFamily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("Father", "Father"),
                            ("Mother", "Mother"),
                            ("Spouse", "Spouse"),
                            ("Child", "Child"),
                            ("Sibling", "Sibling"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("dob", models.DateField(blank=True, null=True)),
                ("occupation", models.CharField(blank=True, max_length=100, null=True)),
                ("aadhaar_no", models.CharField(blank=True, max_length=12, null=True)),
                ("contact_no", models.CharField(blank=True, max_length=15, null=True)),
                ("address", models.CharField(blank=True, max_length=150, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="emp.employee"
                    ),
                ),
            ],
            options={
                "db_table": "employee_family",
            },
        ),
        migrations.CreateModel(
            name="EmployeeExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("job_title", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("responsibilities", models.TextField(blank=True, null=True)),
                (
                    "gross_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("reason_for_leaving", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="emp.employee"
                    ),
                ),
            ],
            options={
                "db_table": "employee_experience",
            },
        ),
        migrations.CreateModel(
            name="EmployeeEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degree", models.CharField(max_length=100)),
                ("institution", models.CharField(max_length=255)),
                ("passing_year", models.IntegerField()),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="emp.employee"
                    ),
                ),
            ],
            options={
                "db_table": "employee_education",
            },
        ),
        migrations.AddConstraint(
            model_name="employeeexperience",
            constraint=models.CheckConstraint(check=models.Q(("end_date__gte", models.F("start_date"))),
                name="check_end_date_gte_start_date",
            ),
        ),
    ]



