# Generated by Django 4.2.9 on 2025-08-26 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp", "0014_employeeadjustment_employeesalarytransaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeadjustment",
            name="remaining_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Active",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="designation",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Active",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="employeeadjustment",
            name="adjustment_type",
            field=models.CharField(
                choices=[
                    ("Advance", "Advance"),
                    ("Fine", "Fine"),
                    ("Bonus", "Bonus"),
                    ("Reward", "Reward"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="employeeadjustment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Partial", "Partial"),
                    ("Cleared", "Cleared"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]



