# Generated by Django 4.2.9 on 2025-09-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0015_employeeadjustment_remaining_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='event_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='event_dob_remark',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='contact1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='contact2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
