# Generated by Django 4.2.9 on 2025-09-15 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0016_contact_event_dob_contact_event_dob_remark_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='event_dob',
            new_name='event_date',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='event_dob_remark',
            new_name='event_date_remark',
        ),
    ]



