# Generated by Django 4.2.9 on 2025-11-22 09:57

import apps.emp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp", "0018_rename_contact_contacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="nopic.jpg",
                null=True,
                upload_to=apps.emp.models.get_photo_upload_path,
            ),
        ),
    ]
