# Generated by Django 4.2.9 on 2025-12-09 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp", "0020_employeeadjustmentmaster_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeadjustmentmaster",
            name="cleared_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]



