# Generated by Django 4.2.9 on 2026-05-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp", "0022_employee_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="driving_license",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="has_aadhaar",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="other_national_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="voter_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("driving_license__isnull", False),
                    models.Q(("driving_license", ""), _negated=True),
                ),
                fields=("driving_license",),
                name="unique_non_empty_driving_license",
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("voter_id__isnull", False),
                    models.Q(("voter_id", ""), _negated=True),
                ),
                fields=("voter_id",),
                name="unique_non_empty_voter_id",
            ),
        ),
    ]



