# Generated by Django 4.2.9 on 2026-05-04 08:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("emp", "0023_employee_driving_license_employee_has_aadhaar_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmploymentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joining_date", models.DateField()),
                ("exit_date", models.DateField(blank=True, null=True)),
                ("department_snapshot", models.CharField(max_length=100)),
                ("designation_snapshot", models.CharField(max_length=100)),
                (
                    "site_snapshot",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("reason_for_exit", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employment_history",
                        to="emp.employee",
                    ),
                ),
            ],
            options={
                "db_table": "employment_history",
                "ordering": ["-joining_date"],
            },
        ),
        migrations.CreateModel(
            name="EmployeePerformanceReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "review_year",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(2000)]
                    ),
                ),
                (
                    "attendance_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "performance_rating",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("manager_comments", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_reviews",
                        to="emp.employee",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_reviews",
                        to="emp.employee",
                    ),
                ),
            ],
            options={
                "db_table": "employee_performance_reviews",
                "unique_together": {("employee", "review_month", "review_year")},
            },
        ),
    ]



