# Generated by Django 6.0.4 on 2026-05-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp", "0025_employee_status_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="aadhaar_no",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="driving_license",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="pan_card",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="passport_no",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="voter_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]



