# Generated by Django 6.0.4 on 2026-05-06 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp", "0026_alter_employee_aadhaar_no_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Profile", "Profile"),
                            ("Status", "Status"),
                            ("Authentication", "Authentication"),
                            ("Academics", "Academics"),
                            ("Documents", "Documents"),
                            ("Salary Master", "Salary Master"),
                            ("Payroll", "Payroll"),
                            ("Adjustments", "Adjustments"),
                            ("HR Operations", "HR Operations"),
                        ],
                        max_length=50,
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("remark", models.TextField(blank=True, null=True)),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="emp.employee",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employee_activity_logs",
                "ordering": ["-performed_at"],
            },
        ),
    ]


